### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [TaCodeTuesday/Week3Activity#1]
Hello, you are missing the app_ideas.md file. But the supposed content of that file is in Week1 Readme.md file. If you could edit and resubmit, that would be great.

**Comment by j-davila** [comment]
> 
> 
> Hello, you are missing the app_ideas.md file. But the supposed content of that file is in Week1 Readme.md file. If you could edit and resubmit, that would be great.

Will do, thank you.

**Comment by j-davila** [comment]
> 
> 
> Hello, you are missing the app_ideas.md file. But the supposed content of that file is in Week1 Readme.md file. If you could edit and resubmit, that would be great.

Created a new repository to house both files https://github.com/TaCodeTuesday/android-mobile-app
